### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by iamvikshan** [LindseyBot/bot#2]
Since it is open source, can i self host it so that i can customize it to the needs of my server?

**Comment by Fabricio20** [comment]
I guess I never ended up answering this, but yes, you can self host this provided you understand how to set it up. It's a standard spring application and docker images are available, it uses JPA for the database so you can swap in any driver if you want and it should also auto create the tables and similar.  The `application.yml` file in the repository should have all necessary variables.

No support will be provided for self hosting of course. I also personally dont think this is a great bot to self host due to how it's designed specifically for very large / several hundred shards deployments. If you need a specific feature for your server you are free to look into how it's implemented and replicate it if necessary in your own bot/codebase, nothing here is made of magic and is usually more complex than necessary due to scaling concerns.

If you just want to self host for a subset of the features (ex: nsfw, minigames or anti-ad), there are several smaller self-hostable bots out there which will work way better and use less resources for your own guild.
